RegisterCommand("drinkcoord", function(source,args,raw)
	x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
	local PlayerName = GetPlayerName()
	TriggerServerEvent("SaveDrinkCoords", PlayerName , x , y , z)
	TriggerEvent('chatMessage', "^1SYSTEM", {255, 255, 255}, "Drink Coordinates saved to file.")
end)

RegisterCommand("foodcoord", function(source,args,raw)
	x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
	local PlayerName = GetPlayerName()
	TriggerServerEvent("SaveFoodCoords", PlayerName , x , y , z)
	TriggerEvent('chatMessage', "^1SYSTEM", {255, 255, 255}, "Food Coordinates saved to file.")
end)

RegisterCommand("lootcoord", function(source,args,raw)
	x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
	local PlayerName = GetPlayerName()
	TriggerServerEvent("SaveLootCoords", PlayerName , x , y , z)
	TriggerEvent('chatMessage', "^1SYSTEM", {255, 255, 255}, "Loot Coordinates saved to file.")
end)

RegisterCommand("pillcoord", function(source,args,raw)
	x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
	local PlayerName = GetPlayerName()
	TriggerServerEvent("SavePillCoords", PlayerName , x , y , z)
	TriggerEvent('chatMessage', "^1SYSTEM", {255, 255, 255}, "Pill Coordinates saved to file.")
end)

RegisterCommand("misccoord", function(source,args,raw)
	x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
	local PlayerName = GetPlayerName()
	TriggerServerEvent("SaveMiscCoords", PlayerName , x , y , z)
	TriggerEvent('chatMessage', "^1SYSTEM", {255, 255, 255}, "Misc Coordinates saved to file.")
end)